!include LogicLib.nsh

; Capture the hook directory while this file is included.  NSIS evaluates
; __FILEDIR__ at macro expansion time as well, which points at Tauri's
; generated staging directory rather than this source directory.
!define SG_HOOK_SOURCE_DIR "${__FILEDIR__}"

!macro SG_RUN_CLEANUP _mode
  File /oname=$PLUGINSDIR\seroguld-installer-cleanup.ps1 "${SG_HOOK_SOURCE_DIR}\seroguld-installer-cleanup.ps1"
  nsExec::ExecToLog '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "$PLUGINSDIR\seroguld-installer-cleanup.ps1" -Mode "${_mode}" -InstalledRoot "$INSTDIR"'
  Pop $0
  ${If} "${_mode}" == "PostInstall"
    ; Defence in depth: the cleanup script migrates this customer-specific
    ; seed and removes it in a finally block.  NSIS also deletes the exact
    ; payload path before handling a failed cleanup exit.
    Delete "$INSTDIR\runtime\seroguld-runtime\runtime-seed.env"
  ${EndIf}
  ${If} $0 != 0
    MessageBox MB_ICONSTOP|MB_OK "Sero Guld CRM eski çalışma süreçleri temizlenemedi. Kurulum durduruldu."
    Abort
  ${EndIf}
  Delete "$PLUGINSDIR\seroguld-installer-cleanup.ps1"
!macroend

!macro NSIS_HOOK_PREINSTALL
  !insertmacro SG_RUN_CLEANUP "PreInstall"
!macroend

!macro NSIS_HOOK_POSTINSTALL
  !insertmacro SG_RUN_CLEANUP "PostInstall"
  ; Tauri's Start Menu shortcut is generated by the bundle, but the desktop
  ; icon is an explicit product requirement.  Recreate both links idempotently
  ; after the files and default shortcuts exist.
  SetShellVarContext all
  CreateDirectory "$SMPROGRAMS\Sero Guld CRM"
  CreateShortCut "$DESKTOP\SERO GULD CRM.lnk" "$INSTDIR\seroguld_crm_desktop.exe"
  CreateShortCut "$SMPROGRAMS\Sero Guld CRM\SERO GULD CRM.lnk" "$INSTDIR\seroguld_crm_desktop.exe"
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  !insertmacro SG_RUN_CLEANUP "PreUninstall"
  SetShellVarContext all
  Delete "$DESKTOP\SERO GULD CRM.lnk"
  Delete "$SMPROGRAMS\Sero Guld CRM\SERO GULD CRM.lnk"
  RMDir "$SMPROGRAMS\Sero Guld CRM"
!macroend
