import { describe, expect, it } from 'vitest';

import { createAlisTransitionBlocker, createLogTransitionBlocker, createOfficeTransitionBlocker } from '@/modern/adapters';
import type { AlisPageProps } from '@/make/alis/AlisPage';
import type { LogPageProps } from '@/make/log/LogPage';
import type { OfficeDocumentPageProps } from '@/make/office/OfficeDocumentPage';

function buildAlisState(partial: Partial<AlisPageProps>): AlisPageProps {
  return {
    pdfState: { url: null, filename: '', loading: false, error: null },
    onClosePdfModal: () => undefined,
    detailPurchase: null,
    detail: null,
    detailLoading: false,
    onCloseDetail: () => undefined,
    onEditDetail: () => undefined,
    onDeleteDetail: () => undefined,
    onExportDetail: () => undefined,
    onPrintDetail: () => undefined,
    onOpenDetailExcelPreview: () => undefined,
    detailActionPending: false,
    workspace: {
      session: { id: 'w1', session_code: 'S-1', display_token: 'd', trade_side: 'buy_from_customer', rate_source: 'live', margin_percent_internal: '0', status: 'draft', created_at: '', updated_at: '' },
      customer: { name: 'Ada' },
      bank_info: {},
      payment_method: 'bank',
      market_rates: { eur_dkk_fx: '', gold_rates_dkk: {}, silver_rates_dkk: {}, gold_24k_dkk: '', silver_dkk: '', gold_matrix: [], silver_matrix: [] },
      calculators: { gold_rows: [], silver_rows: [] },
      numbering_preview: { product_number_next: '', reference_number_next: '', afregnings_number_next: '', invoice_number_next: '' },
      invoice_gold_mode: 'auto',
      gold_rows: [],
      silver_rows: [],
      invoice_gold: { rows: [], footer_lines: [], total_grams: '0', total_amount_dkk: '0' },
      invoice_misc_mode: 'auto',
      invoice_misc: { rows: [], total_amount_dkk: '0' },
      quick_mode_editable: true,
      purchase_vat_enabled: true,
      purchase_vat_rate_percent: '25',
      summary: { active_line_count: 0, total_weight_grams: '0', total_pure_gold_grams: '0', gold_weight_grams: '0', silver_weight_grams: '0', total_amount_dkk: '0', net_amount_dkk: '0', vat_rate_percent: '25', vat_amount_dkk: '0', gross_amount_dkk: '0' },
    },
    draftWorkspace: null,
    onResumeDraft: () => undefined,
    documents: [],
    purchaseSearchTerm: '',
    setPurchaseSearchTerm: () => undefined,
    purchaseDate: '',
    setPurchaseDate: () => undefined,
    onOpenCustomer: () => undefined,
    onViewDocument: () => undefined,
    onOpenDocumentExcelPreview: () => undefined,
    onExportDocument: () => undefined,
    onPrintDocument: () => undefined,
    onStartFromCustomer: () => undefined,
    onEditDocument: () => undefined,
    onDeleteDocument: () => undefined,
    onRetryUnicontaSync: () => undefined,
    retryPendingSequenceNo: null,
    onCancelUnicontaInvoice: () => undefined,
    cancelPendingSequenceNo: null,
    listLoading: false,
    actionPendingSequenceNo: null,
    customerMode: null,
    setCustomerMode: () => undefined,
    customerSearchTerm: '',
    setCustomerSearchTerm: () => undefined,
    candidateCustomers: [],
    newCustomer: { name: '', email: '', phone: '', address: '', postal_code: '', city: '', cpr_number: '', identity_doc_type: '', identity_doc_number: '', identity_doc_country: '' },
    setNewCustomer: () => undefined,
    onSelectExistingCustomer: () => undefined,
    onCreateNewCustomer: () => undefined,
    customerForm: { name: '', email: '', phone: '', address: '', postal_code: '', city: '', cpr_number: '', identity_doc_type: '', identity_doc_number: '', identity_doc_country: '' },
    setCustomerForm: () => undefined,
    onCustomerBlur: () => undefined,
    goldRows: [],
    silverRows: [],
    barRows: [],
    onUpdateBarRow: () => undefined,
    onUpdateGoldRow: () => undefined,
    onUpdateSilverRow: () => undefined,
    activeWorkspaceView: 'system',
    setActiveWorkspaceView: () => undefined,
    numbering: { afregnings_number_next: '', invoice_number_next: '' },
    setNumbering: () => undefined,
    onUpdateNumbering: () => undefined,
    invoiceGoldMode: 'auto',
    invoiceGoldRows: [],
    invoiceGoldFooterLines: [],
    onUpdateInvoiceGoldRow: () => undefined,
    onUpdateInvoiceGoldFooterLine: () => undefined,
    onResetInvoiceGoldToAuto: () => undefined,
    invoiceMiscMode: 'auto',
    invoiceMiscRows: [],
    onUpdateInvoiceMiscRow: () => undefined,
    onResetInvoiceMiscToAuto: () => undefined,
    bankInfo: {},
    setBankInfo: () => undefined,
    marketRates: { eur_dkk_fx: '', gold_rates_dkk: {}, silver_rates_dkk: {}, gold_24k_dkk: '', silver_dkk: '', gold_matrix: [], silver_matrix: [] },
    setMarketRates: () => undefined,
    afgNote: '',
    setAfgNote: () => undefined,
    purchaseVatEnabled: true,
    setPurchaseVatEnabled: () => undefined,
    calculators: { gold_rows: [], silver_rows: [] },
    setCalculators: () => undefined,
    paymentMethod: 'bank',
    setPaymentMethod: () => undefined,
    onPrintWorkspace: () => undefined,
    onOpenWorkspaceExcelPreview: () => undefined,
    onCancelWorkspace: () => undefined,
    onFinalizeWorkspace: () => undefined,
    customerPending: false,
    customerSelecting: false,
    finalizePending: false,
    cancelPending: false,
    onStartBlankWorkspace: () => undefined,
    startPending: false,
    priceOpen: false,
    setPriceOpen: () => undefined,
    ...partial,
  };
}

function buildLogState(partial: Partial<LogPageProps>): LogPageProps {
  return {
    isLoading: false,
    isError: false,
    onRetryWorkspace: () => undefined,
    activeView: 'system',
    onActiveViewChange: () => undefined,
    activeTab: 'gold',
    onActiveTabChange: () => undefined,
    query: '',
    onQueryChange: () => undefined,
    expandedDocument: null,
    onToggleDocument: () => undefined,
    showMeltSection: false,
    onToggleMeltSection: () => undefined,
    lineDrafts: {},
    onDraftChange: () => undefined,
    lotDrafts: {},
    onLotDraftChange: () => undefined,
    routeBusy: false,
    meltBusy: false,
    createMeltBusy: false,
    finalizeBusy: false,
    deleteBusy: false,
    pendingRouteCount: 0,
    pendingRouteSummary: { count: 0, weight: 0, amount: 0, pure: 0 },
    onDiscardRouteReview: () => undefined,
    onApplyRouteReview: () => undefined,
    onRoute: () => undefined,
    onSaveLot: () => undefined,
    onCreateMeltLot: () => undefined,
    onFinalizeLot: () => undefined,
    onDeleteLot: () => undefined,
    onDownloadLotPdf: () => undefined,
    onOpenLotHistory: () => undefined,
    onCloseLotHistory: () => undefined,
    historyLotId: null,
    lotHistory: [],
    lotHistoryLoading: false,
    onOpenLotLines: () => undefined,
    onCloseLotLines: () => undefined,
    linesLotId: null,
    lotLines: [],
    lotLinesLoading: false,
    selectedYear: 2026,
    onSelectedYearChange: () => undefined,
    ...partial,
  };
}

function buildOfficeState(partial: Partial<OfficeDocumentPageProps>): OfficeDocumentPageProps {
  return {
    kind: 'alis-workspace',
    artifactKey: 'w1',
    launch: null,
    status: null,
    runtimeStatus: null,
    appRuntimeStatus: null,
    desktopRuntime: null,
    frontendRuntime: { frontend_mode: 'vite-dev', frontend_built_at: '2026-08-06T00:00:00Z', api_base_url: 'http://127.0.0.1:8100' },
    runtimeWarnings: [],
    iframeName: 'office',
    formRef: { current: null },
    useNativeImportDialog: false,
    isLoading: false,
    isError: false,
    isImporting: false,
    isStatusRefreshing: false,
    isSessionRefreshing: false,
    isIframeLoading: false,
    hasIframeLoadTimedOut: false,
    launchRequestMs: null,
    iframeLoadMs: null,
    sessionRefreshMs: null,
    isSessionStale: false,
    canReopenWindow: false,
    hasExternalUpdate: false,
    lastImportError: null,
    lastExportNotice: null,
    lastExportError: null,
    lastEditorError: null,
    onExport: () => undefined,
    onImportFromDialog: () => undefined,
    onImportFile: () => undefined,
    onRefreshStatus: () => undefined,
    onRefreshSession: () => undefined,
    onReopenWindow: () => undefined,
    onIframeLoad: () => undefined,
    onEditorError: () => undefined,
    ...partial,
  };
}

describe('modern transition blockers', () => {
  it('builds alis blocker reasons from pending operations', () => {
    const blocker = createAlisTransitionBlocker(buildAlisState({ customerPending: true, finalizePending: true }), { hasPendingAutosave: true });
    expect(blocker?.when).toBe(true);
    expect(blocker?.reasons).toContain('Otomatik kaydetme kuyruğu henüz tamamlanmadı');
    expect(blocker?.reasons).toContain('Müşteri kartı güncelleniyor');
    expect(blocker?.severity).toBe('danger');
  });

  it('builds log blocker when route review is pending', () => {
    const blocker = createLogTransitionBlocker(buildLogState({ pendingRouteCount: 3, pendingRouteSummary: { count: 3, weight: 10, amount: 20, pure: 5 } }));
    expect(blocker?.when).toBe(true);
    expect(blocker?.reasons[0]).toContain('3 rota taslağı');
  });

  it('builds office blocker for dirty sync conflict', () => {
    const blocker = createOfficeTransitionBlocker(buildOfficeState({ isLivePreviewDirty: true, isLivePreviewSyncing: true, hasExternalUpdate: true }), { isDirty: true });
    expect(blocker?.when).toBe(true);
    expect(blocker?.reasons.length).toBeGreaterThanOrEqual(2);
  });
});
